### ISSUE TITLE
Error about convert  " KeyError: 'log1p'  "

### ISSUE THREAD

**Issue by Sawakotx** [pigudog/scPDtools#1]
Hi, I am very happy to see your post on WeChat for this tool.
But When I convert anndata to seurat, I found some error here.
There are some details.
I ran these code in scanpy:
`adata_epi.layers['log1p'] = adata_epi.X.copy()
adata_epi.write(f"/PROJECT/0.scanpy/Epi_after_for_inferCNV_2024-11-05.h5ad") `

AND I ran these codes in R (Windows).
```
use_condaenv("scanpy2seurat")
> convertFormat('E:/workshop/infercnv/Epi_after_for_inferCNV_2024-11-05.h5ad'
+               , from="anndata", to="seurat",main_layer = "counts_log1p",
+               outFile='E:/workshop/scanpy/1.inferCNV_epi_test.rds')
Error in (function (cond)  : 
  在为't'函数选择方法时评估'x'参数出了错: KeyError: 'log1p'
```
Looking forward to your reply, any suggestions will be helpful!

**Comment by pigudog** [comment]
It seems that the issue is due to the naming mismatch of the main_layer parameter in your convertFormat function. 

Check if the log1p layer is correctly stored: In your Scanpy code, ensure that the adata_epi.layers['log1p'] contains the correct log-transformed data. You can print out the keys of adata_epi.layers to confirm:

```print(adata_epi.layers.keys())```

I think maybe the count layer is missing？In general, if I did not add the count layer to the layer before, I will directly input the log1p layer to the count layer(As a way to prevent an error but it's not correct):

```
adata_counts=adata_I_r.raw.to_adata().copy()
adata_counts

adata_counts.layers["counts"] = adata_counts.X.copy()
adata_counts.layers["log1p"] = adata_counts.X.copy()

adata_counts.write_h5ad("pydata/adata_I_compare.h5ad")
```

**Comment by Sawakotx** [comment]
Thank your timely reply！
It work! Thanks a lot!!!!
I just ran `adata_counts.layers["log1p"] = adata_counts.X.copy()` and write_h5ad again. There are some details maybe help other people.

Before converting, I ran the following codes to preprocess in the subcluster analysis.
```
adata_epi.X = adata_epi.layers['counts'].copy()
# Normalization
sc.pp.normalize_total(adata_epi)
sc.pp.log1p(adata_epi)

# Batch effect Correction
sc.pp.highly_variable_genes(adata_epi, n_top_genes=5000, batch_key="sample_id", flavor='seurat_v3')
```

AND 
To ensure my adata_epi contains what layers (following your advice), I ran these codes below.
```
adata_epi.X.max()
# 6.9516716
adata_epi.layers["counts"].max()
# 13019.0

adata_epi.layers['log1p'] = adata_epi.X.copy()
print(adata_epi.layers.keys())` , its output is `KeysView(Layers with keys: counts)
```

THEN, when I try to set main_layer = "counts" or "counts_log1p", it can work!!!
```
convertFormat('/workshop/Epi_after_interg_2024-11-05.h5ad'
+ , from="anndata", to="seurat",main_layer = "counts",
+               outFile='/scanpy/epi_test.rds')
X -> counts 
```

But I have another question about `**SCP packages**`, I just install `**scPDtools**` and when I ran CellDimPlot() function, I found only install scPDtools seems not to install SCP in the same time. I want to ask if this is right? 
```
Error in CellDimPlot(srt = adata, group.by = c("sub_celltype", "sample_id"),  : 
  没有"CellDimPlot"这个函数
```

Also，I'd like to ask if you can provide some tips on how to properly install SCP, as the SCP R package seems to be a bit difficult to install. Thanks ~~~

**Comment by pigudog** [comment]
SCP is no longer supported in the current version, and this package may be replaced with new visualization methods in the future. Thank you for your support and usage~
